### ISSUE TITLE
Trollius - deprecated module (Doesn't work with Python 3)

### ISSUE THREAD

**Issue by akouri-dd** [PRBonn/rangenet_lib#11]
Hi,

Thanks for the great writeup and paper. I am trying to replicate your results on my Ubuntu 18.04 machine with NVIDIA GTX 1080ti. I am following the installation instructions, but run into a hiccup at the `catkin_build` step.

```
ddlabs@ddlabs-All-Series:~/catkin_ws$ catkin build rangenet_lib
-----------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/melodic
Workspace:                   /home/ddlabs/catkin_ws
-----------------------------------------------------------
Build Space:        [exists] /home/ddlabs/catkin_ws/build
Devel Space:        [exists] /home/ddlabs/catkin_ws/devel
Install Space:      [unused] /home/ddlabs/catkin_ws/install
Log Space:          [exists] /home/ddlabs/catkin_ws/logs
Source Space:       [exists] /home/ddlabs/catkin_ws/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found '2' packages in 0.0 seconds.                                                          
[build] Package table is up to date.                                                                
Starting  >>> catkin                                                                                
Finished  <<< catkin                      [ 0.1 seconds ]                                           
Starting  >>> rangenet_lib                                                                          
Finished  <<< rangenet_lib                [ 0.3 seconds ]                                           
[build] Summary: All 2 packages succeeded!                                                          
[build]   Ignored:   None.                                                                          
[build]   Warnings:  None.                                                                          
[build]   Abandoned: None.                                                                          
[build]   Failed:    None.                                                                          
[build] Runtime: 0.5 seconds total.                                                                 
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/ddlabs/.local/lib/python3.6/site-packages/trollius/base_events.py", line 395, in __del__
  File "/home/ddlabs/.local/lib/python3.6/site-packages/trollius/unix_events.py", line 65, in close
  File "/home/ddlabs/.local/lib/python3.6/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by tano297** [comment]
The build says that both packages succeeded. This is a known issue in Python 3, but it does not affect the build.
